import type { ExtractedDeckCard } from '@/types'

const MOCK_EXTRACTED_DECK: ExtractedDeckCard[] = [
  {
    id: 'mock-pokemon-dragapult-ex',
    quantity: 2,
    name: 'Dragapult ex',
    setCode: 'DRI',
    cardNumber: '130',
    regulationMark: 'I',
    category: 'Pokemon',
    confidence: 0.98,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-dreepy',
    quantity: 3,
    name: 'Dreepy',
    setCode: 'TWM',
    cardNumber: '128',
    regulationMark: 'H',
    category: 'Pokemon',
    confidence: 0.95,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-drakloak',
    quantity: 2,
    name: 'Drakloak',
    setCode: 'TWM',
    cardNumber: '129',
    regulationMark: 'H',
    category: 'Pokemon',
    confidence: 0.94,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-fezandipiti-ex',
    quantity: 1,
    name: 'Fezandipiti ex',
    setCode: 'SFA',
    cardNumber: '038',
    regulationMark: 'H',
    category: 'Pokemon',
    confidence: 0.91,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-radiant-charizard',
    quantity: 1,
    name: 'Radiant Charizard',
    setCode: 'CRZ',
    cardNumber: '020',
    regulationMark: 'F',
    category: 'Pokemon',
    confidence: 0.88,
    legalityStatus: 'not_standard',
    notes: ['Non-standard card detected in mock extraction.'],
  },
  {
    id: 'mock-pokemon-pidgey',
    quantity: 2,
    name: 'Pidgey',
    setCode: 'MEW',
    cardNumber: '016',
    regulationMark: 'G',
    category: 'Pokemon',
    confidence: 0.93,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-pidgeot-ex',
    quantity: 2,
    name: 'Pidgeot ex',
    setCode: 'OBF',
    cardNumber: '164',
    regulationMark: 'G',
    category: 'Pokemon',
    confidence: 0.96,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-pokemon-rotom-v',
    quantity: 1,
    name: 'Rotom V',
    setCode: 'LOR',
    cardNumber: '058',
    regulationMark: 'F',
    category: 'Pokemon',
    confidence: 0.9,
    legalityStatus: 'not_standard',
    notes: ['Older regulation mark, included as a warning example.'],
  },
  {
    id: 'mock-pokemon-ogerpon-pre',
    quantity: 1,
    name: 'Cornerstone Mask Ogerpon ex',
    setCode: 'PRE',
    cardNumber: '160',
    regulationMark: 'H',
    category: 'Pokemon',
    confidence: 0.72,
    legalityStatus: 'unknown',
    notes: ['Possible duplicate print. Confirm set code and card number.'],
  },
  {
    id: 'mock-pokemon-ogerpon-twm',
    quantity: 1,
    name: 'Cornerstone Mask Ogerpon ex',
    setCode: 'TWM',
    cardNumber: '112',
    regulationMark: 'H',
    category: 'Pokemon',
    confidence: 0.63,
    legalityStatus: 'standard',
    notes: ['Duplicate-print candidate found in the same deck image.'],
  },
  {
    id: 'mock-trainer-buddy-poffin',
    quantity: 4,
    name: 'Buddy-Buddy Poffin',
    setCode: 'TWM',
    cardNumber: '223',
    regulationMark: 'H',
    category: 'Trainer',
    confidence: 0.99,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-rare-candy',
    quantity: 4,
    name: 'Rare Candy',
    setCode: 'PAF',
    cardNumber: '089',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.98,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-ultra-ball',
    quantity: 3,
    name: 'Ultra Ball',
    setCode: 'PAF',
    cardNumber: '091',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.97,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-nest-ball',
    quantity: 2,
    name: 'Nest Ball',
    setCode: 'SVI',
    cardNumber: '181',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.96,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-counter-catcher',
    quantity: 2,
    name: 'Counter Catcher',
    setCode: 'PAR',
    cardNumber: '160',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.94,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-super-rod',
    quantity: 2,
    name: 'Super Rod',
    setCode: 'PAL',
    cardNumber: '188',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.93,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-earthen-vessel',
    quantity: 1,
    name: 'Earthen Vessel',
    setCode: 'PAR',
    cardNumber: '163',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.88,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-night-stretcher',
    quantity: 1,
    name: 'Night Stretcher',
    setCode: 'SFA',
    cardNumber: '061',
    regulationMark: 'H',
    category: 'Trainer',
    confidence: 0.84,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-iono',
    quantity: 2,
    name: 'Iono',
    setCode: 'PAF',
    cardNumber: '080',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.96,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-arven',
    quantity: 2,
    name: 'Arven',
    setCode: 'OBF',
    cardNumber: '186',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.95,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-boss',
    quantity: 1,
    name: "Boss's Orders",
    setCode: 'PAL',
    cardNumber: '172',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.9,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-turo',
    quantity: 1,
    name: "Professor Turo's Scenario",
    setCode: 'PAR',
    cardNumber: '171',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.87,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-tm-evolution',
    quantity: 2,
    name: 'Technical Machine: Evolution',
    setCode: 'PAR',
    cardNumber: '178',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.79,
    legalityStatus: 'standard',
    notes: ['Medium-confidence read, confirm the card name.'],
  },
  {
    id: 'mock-trainer-forest-seal-stone',
    quantity: 2,
    name: 'Forest Seal Stone',
    setCode: 'SIT',
    cardNumber: '156',
    regulationMark: 'F',
    category: 'Trainer',
    confidence: 0.76,
    legalityStatus: 'not_standard',
    notes: ['Non-standard card detected in mock extraction.'],
  },
  {
    id: 'mock-trainer-artazon',
    quantity: 2,
    name: 'Artazon',
    setCode: 'PAF',
    cardNumber: '076',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.91,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-trainer-switch',
    quantity: 3,
    name: 'Switch',
    setCode: 'SVI',
    cardNumber: '194',
    regulationMark: 'G',
    category: 'Trainer',
    confidence: 0.86,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-energy-psychic',
    quantity: 6,
    name: 'Basic {P} Energy',
    setCode: 'SVE',
    cardNumber: '005',
    category: 'Energy',
    confidence: 0.97,
    legalityStatus: 'standard',
  },
  {
    id: 'mock-energy-fire',
    quantity: 4,
    name: 'Basic {R} Energy',
    setCode: 'SVE',
    cardNumber: '002',
    category: 'Energy',
    confidence: 0.92,
    legalityStatus: 'standard',
  },
]

export async function parseDeckImageMock(): Promise<ExtractedDeckCard[]> {
  return MOCK_EXTRACTED_DECK.map((card) => ({
    ...card,
    notes: card.notes ? [...card.notes] : undefined,
  }))
}
